spring.datasource.url=jdbc:postgresql://localhost:5432/tasks_db
spring.datasource.username=postgres
spring.datasource.password=1910Mb30r717
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true